server:
  port: 8083

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://localhost:5435/auth_db
    username: user_auth
    password: password_auth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
