services:
  # --- BASES DE DATOS ---
  db-products:
    image: postgres:15
    container_name: db-products
    environment:
      POSTGRES_USER: user_prod
      POSTGRES_PASSWORD: password_prod
      POSTGRES_DB: products_db
    ports:
      - "5433:5432"
    networks:
      - ecommerce-network
    volumes:
      - db_products_data:/var/lib/postgresql/data

  db-orders:
    image: postgres:15
    container_name: db-orders
    environment:
      POSTGRES_USER: user_order
      POSTGRES_PASSWORD: password_order
      POSTGRES_DB: orders_db
    ports:
      - "5434:5432"
    networks:
      - ecommerce-network
    volumes:
      - db_orders_data:/var/lib/postgresql/data

  db-auth:
    image: postgres:15
    container_name: db-auth
    environment:
      POSTGRES_USER: user_auth
      POSTGRES_PASSWORD: password_auth
      POSTGRES_DB: auth_db
    ports:
      - "5435:5432"
    networks:
      - ecommerce-network
    volumes:
      - db_auth_data:/var/lib/postgresql/data

  # --- INFRAESTRUCTURA SPRING CLOUD ---
  eureka-server:
    build: ./discovery-server
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - ecommerce-network

  # --- MICROSERVICIOS DE NEGOCIO ---
  product-service:
    build: ./product-service
    container_name: product-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-products:5432/products_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - db-products
      - eureka-server
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    container_name: order-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-orders:5432/orders_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - db-orders
      - eureka-server
    networks:
      - ecommerce-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-auth:5432/auth_db
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - db-auth
      - eureka-server
    networks:
      - ecommerce-network

  # --- FRONTEND ---
  #frontend:
   
   # build: ./frontend-react
    #container_name: frontend-react
    #ports:
     # - "5173:5173"
    #depends_on:
     # - api-gateway
    #networks:
     # - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  db_products_data:
  db_orders_data:
  db_auth_data: