server:
  port: 8080

spring:
  application:
    name: api-gateway
  threads:
    virtual:
      enabled: true
  
  cloud:
    gateway:
      # Configuración de Rutas
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/products/**
            
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

      # Configuración de CORS para tu React App
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173" # Puerto por defecto de Vite
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"

# Registro en el Servidor de Descubrimiento (Eureka)
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    # Configuraciones para mejorar la conexión inicial
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    instance-info-replication-interval-seconds: 5
  instance:
    hostname: localhost
    # Configuraciones para mejorar el registro
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30