server:
  port: 8082

spring:
  application:
    name: order-service
  
  datasource:
    url: jdbc:postgresql://localhost:5434/orders_db # Puerto 5434 (según el compose)
    username: user_order
    password: password_order
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/