server:
  port: 8081 # Cada microservicio debe tener un puerto distinto localmente

spring:
  application:
    name: product-service
  
  # Configuración de Base de Datos (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/products_db # Puerto 5433 según el compose anterior
    username: user_prod
    password: password_prod
  
  jpa:
    hibernate:
      ddl-auto: update # Crea las tablas automáticamente basado en tus clases Java
    show-sql: true # Para ver las consultas en la consola mientras desarrollas
  
  # Activar hilos virtuales de Java 21
  threads:
    virtual:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/